# Generated by Django 3.1.6 on 2021-02-06 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Connector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='名前')),
            ],
        ),
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='名前')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='supply.standard', verbose_name='親規格')),
            ],
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('C', 'ケーブル'), ('E', '電化製品')], max_length=2, verbose_name='分類')),
                ('number', models.IntegerField(verbose_name='番号')),
                ('category', models.CharField(blank=True, max_length=40, null=True, verbose_name='種類')),
                ('name', models.CharField(blank=True, max_length=40, null=True, verbose_name='名前')),
                ('manufacturer', models.CharField(blank=True, max_length=40, null=True, verbose_name='メーカー')),
                ('model', models.CharField(blank=True, max_length=40, null=True, verbose_name='型番')),
                ('serial_number', models.CharField(blank=True, max_length=200, null=True, verbose_name='シリアルナンバー')),
                ('length', models.IntegerField(blank=True, null=True, verbose_name='長さ(cm)')),
                ('bought_at', models.DateField(blank=True, null=True, verbose_name='購入日')),
                ('position', models.TextField(blank=True, null=True, verbose_name='設置場所')),
                ('is_power_cable', models.BooleanField(default=False, verbose_name='電源線か')),
                ('is_signal_cable', models.BooleanField(default=False, verbose_name='信号線か')),
                ('is_active_cable', models.BooleanField(default=False, verbose_name='アクティブケーブルか')),
                ('note', models.TextField(blank=True, null=True, verbose_name='備考')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.localtime, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.localtime, verbose_name='更新日')),
                ('connected_supplies', models.ManyToManyField(blank=True, related_name='_supply_connected_supplies_+', to='supply.Supply', verbose_name='接続先')),
            ],
        ),
        migrations.CreateModel(
            name='SupplyConnectorRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('None', '未定義'), ('Male', 'オス'), ('Female', 'メス')], max_length=10, null=True, verbose_name='オス・メス')),
                ('count', models.IntegerField(default=1, verbose_name='個数')),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_relations', to='supply.connector', verbose_name='コネクタ')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connector_relations', to='supply.supply', verbose_name='製品')),
            ],
        ),
        migrations.AddField(
            model_name='supply',
            name='connectors',
            field=models.ManyToManyField(blank=True, related_name='supplies', through='supply.SupplyConnectorRelation', to='supply.Connector', verbose_name='コネクタ'),
        ),
        migrations.AddField(
            model_name='supply',
            name='last_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='最終更新者'),
        ),
        migrations.AddField(
            model_name='supply',
            name='owner',
            field=models.ManyToManyField(blank=True, related_name='supplies', to=settings.AUTH_USER_MODEL, verbose_name='所有者'),
        ),
        migrations.AddField(
            model_name='supply',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='supply.supply', verbose_name='本体'),
        ),
        migrations.AddField(
            model_name='supply',
            name='standard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplies', to='supply.standard', verbose_name='規格'),
        ),
        migrations.AddField(
            model_name='connector',
            name='standard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supply.standard', verbose_name='規格'),
        ),
    ]
