# Generated by Django 3.1.6 on 2021-02-12 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0003_auto_20210212_0952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supply',
            name='standard',
        ),
    ]
